<?php

declare(strict_types=1);


namespace App\Design\Behavioral\State;


use phpDocumentor\Reflection\Types\Static_;

class ContextOrder extends StateOrder
{
    /**
     * @return StateOrder
     */
    public static function getState(): StateOrder
    {
        return static::$state;
    }

    protected function setStates(string $status)
    {
        static::$state = $status;
    }


    protected function done()
    {
        static::$state->done();
    }

    protected function getStatus(): string
    {
        return static::$state->getStatus(); // TODO: Change the autogenerated stub
    }
}